apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: http-server
  template:
    metadata:
      annotations:
      labels:
        app: http-server
        name: http-server
        version: v2
    spec:
      imagePullSecrets:
        - name: default-secret 
      containers:
        - name: http-server
          image: "swr.ru-moscow-1.hc.sbercloud.ru/sber/http-server:1.0"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          ports:
            - containerPort: 8686
              protocol: TCP
          envFrom:
            - configMapRef:
                name: http-server-config
          volumeMounts:
            - name: application-config
              mountPath: "/deployments/config"
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: http-server-config
            items:
              - key: application.properties
                path: application.properties